sys:
  version: 1.0
qinliu: 
  accessKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  secretKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  bucket: xiaoandx
  
logging.level.club.xiaoandx: DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scstcss_data?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 600000
      idle-timeout: 60000
      validation-timeout: 1000
      leak-detection-threshold: 30000
  redis:
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        jedis:
          pool:
            #连接池最大连接数（使用负值表示没有限制）
            max-active: 100
            # 连接池中的最小空闲连接
            max-idle: 10
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: 100000
        # 连接超时时间（毫秒）
        timeout: 5000
        #默认是索引为0的数据库
        database: 0 
      
#pagehelper:
#    helperDialect: Mysql
#    reasonable: true
#    supportMethodsArguments: true
#    pageSizeZero: true
#    params: count=countSql      
      
server:
#  port: 80
  tomcat:
    accesslog:
      enabled: true
      directory: C:/log/scsstcss/yml
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: scsstcss_access
      suffix: .log
    basedir: C:/log/scsstcss/tomcat
