sys:
  version: 1.0
qinliu: 
  accessKey: 7mYw774OhImScvEks6XR3TAtSp87P68_oiUbfcMb
  secretKey: fJUdt_T7pX_Vib-Y-BlpKtl2JT7tet1xl2PDq8O2
  bucket: xiaoandx
  
logging.level.club.xiaoandx: DEBUG





spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scstcss_data?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 2324671838
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 600000
      idle-timeout: 60000
      validation-timeout: 1000
      leak-detection-threshold: 30000
      
#pagehelper:
#    helperDialect: Mysql
#    reasonable: true
#    supportMethodsArguments: true
#    pageSizeZero: true
#    params: count=countSql      
      
server:
#  port: 80
  tomcat:
    accesslog:
      enabled: true
      directory: C:/log/scsstcss/yml
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: scsstcss_access
      suffix: .log
    basedir: C:/log/scsstcss/tomcat